package com.gangweedganggang.cs4240.backend;

import com.gangweedganggang.cs4240.flowgraph.Local;
import com.gangweedganggang.cs4240.stdlib.collections.graph.FastGraphVertex;

public abstract class TargetReg extends Local implements FastGraphVertex {
    public TargetReg(int index, RegType type) {
        super(index, type);
    }

	// basiaclly, whether this is a temporary register that should be allocated by register allocator,
	// or it's like a hard-coded register generated by the target. for example, the sp is just like,
	// the sp. the register allocator shouldn't touch it.
	abstract public boolean isPhysicalRegister();

	abstract public boolean isZeroRegister();

	abstract public boolean isCalleeSaved();

    // LMAO
	@Override
	public int getNumericId() {
		return getIndex();
	}

	public String getDisplayName() {
		return toString();
	}
}
